#!/bin/sh

if [ $# -ne 1 ]; then
  echo "Usage: ${0##*/} SRCDIR" >&2
  exit 64
fi

if [ ! -d "$1" ]; then
  printf '%s is not a directory\n' "$1" >&2
  exit 1
fi

cd "$1" && exec tube-client initiate rsync --server --daemon \
  --config /dev/fd/3 --log-file /dev/null . 3<<EOF
[src]
  path = .
  read only = 1
  use chroot = 0
EOF
