#!/bin/sh

if [ $# -eq 1 ] && [ "$1" = "invite" ] && STATE=$(stty -g); then
  stty raw -echo && tube-client initiate \
    sh -c 'script -q /dev/null | tee /dev/tty'
  EXIT=$? && printf '\r' && stty $STATE
  exit $EXIT
fi

if [ $# -eq 1 ] && [ "$1" = "login" ] && STATE=$(stty -g); then
  stty raw -echo && tube-client respond
  EXIT=$? && printf '\r' && stty $STATE
  exit $EXIT
fi

echo "Usage: ${0##*/} (invite|login)" >&2
exit 64
